destroy dev

diff --git a/.github/workflows/aws_tf_apply.yml b/.github/workflows/aws_tf_apply.yml
--- a/.github/workflows/aws_tf_apply.yml
+++ b/.github/workflows/aws_tf_apply.yml
@@ -68,17 +68,17 @@ jobs:
         id: validate
         run: terraform validate
 
-      - name: Terraform Plan
-        id: plan
-        run: terraform plan
-        continue-on-error: true
+      # - name: Terraform Plan
+      #   id: plan
+      #   run: terraform plan
+      #   continue-on-error: true
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
-      - name: Terraform Apply
-        run: terraform apply -auto-approve
+      # - name: Terraform Apply
+      #   run: terraform apply -auto-approve
 
       - name: Terraform destroy
         run: terraform destroy --auto-approve
